tunnel: 8eb053d2-9fee-4d55-884b-a6715ae22cbd

ingress:
  - hostname: proyectonube.xyz
    service: http://gateway:80
  - hostname: www.proyectonube.xyz
    service: http://gateway:80
  - service: http_status:404
